<script lang="ts">
  /**
   * Component generated by Kimi K3. Do not edit this file directly.
   *
   * QR scanner drawer content.
   *
   * The camera lifecycle is driven by the drawer's `open` prop — NOT by
   * component mount — because bits-ui only gates the drawer's inner DOM on
   * close; this component instance stays mounted for the page's lifetime.
   * Scans frames with jsQR on a 300 ms interval and reports the first
   * decoded value via `onScan`.
   */

  // ── Third-party ───────────────────────────────────────────────────────
  import jsQR from 'jsqr';

  // ── Utilities ─────────────────────────────────────────────────────────
  import { cn } from '$lib/utils';

  // ── Component imports from $lib ───────────────────────────────────────
  import * as Drawer from '$lib/components/ui/drawer';
  import { Button, buttonVariants } from '$lib/components/ui/button';

  // ── Icon imports from $lib ────────────────────────────────────────────
  import { QrCode01Icon } from '$lib/icons';

  let { open, onScan }: { open: boolean; onScan: (value: string) => void } = $props();

  type CameraStatus = 'starting' | 'scanning' | 'error';

  let status = $state<CameraStatus>('starting');
  let errorMessage = $state('');
  let videoEl = $state<HTMLVideoElement>();

  let stream: MediaStream | null = null;
  let scanTimer: ReturnType<typeof setInterval> | null = null;
  let canvas: HTMLCanvasElement | null = null;
  /**
   * Incremented per start attempt. An async getUserMedia that resolves for a
   * stale session (drawer closed/reopened meanwhile) releases its stream
   * instead of attaching it.
   */
  let session = 0;

  async function startCamera() {
    stopCamera(); // idempotent: never hold two streams
    const current = ++session;
    status = 'starting';
    errorMessage = '';

    if (!navigator.mediaDevices?.getUserMedia) {
      status = 'error';
      errorMessage = 'Camera access requires a secure (HTTPS) connection.';
      return;
    }

    let nextStream: MediaStream;
    try {
      nextStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment' },
        audio: false,
      });
    } catch (err) {
      // Devices without a rear camera reject `facingMode: environment` — retry with any camera.
      if (err instanceof DOMException && err.name === 'OverconstrainedError') {
        try {
          nextStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });
        } catch (retryErr) {
          handleCameraError(retryErr);
          return;
        }
      } else {
        handleCameraError(err);
        return;
      }
    }

    // Drawer was closed (or reopened) while waiting for the permission prompt.
    if (current !== session) {
      nextStream.getTracks().forEach((track) => track.stop());
      return;
    }

    stream = nextStream;
    if (videoEl) {
      videoEl.srcObject = stream;
      await videoEl.play().catch(() => {});
      status = 'scanning';
      scanTimer = setInterval(scanFrame, 300);
    }
  }

  function stopCamera() {
    session++; // invalidate any in-flight getUserMedia
    if (scanTimer) {
      clearInterval(scanTimer);
      scanTimer = null;
    }
    stream?.getTracks().forEach((track) => track.stop());
    stream = null;
    if (videoEl) videoEl.srcObject = null;
  }

  function handleCameraError(err: unknown) {
    status = 'error';
    if (err instanceof DOMException && err.name === 'NotAllowedError') {
      errorMessage =
        'Camera permission was denied. Allow camera access in your browser settings, then try again.';
    } else if (err instanceof DOMException && err.name === 'NotFoundError') {
      errorMessage = 'No camera was found on this device.';
    } else {
      errorMessage = 'The camera could not be started. Please try again.';
    }
  }

  function scanFrame() {
    if (!videoEl || videoEl.readyState < videoEl.HAVE_ENOUGH_DATA) return;

    const { videoWidth: width, videoHeight: height } = videoEl;
    if (!width || !height) return;

    canvas ??= document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;

    const ctx = canvas.getContext('2d', { willReadFrequently: true });
    if (!ctx) return;

    ctx.drawImage(videoEl, 0, 0, width, height);
    const imageData = ctx.getImageData(0, 0, width, height);
    const code = jsQR(imageData.data, width, height, { inversionAttempts: 'dontInvert' });

    if (code?.data) {
      stopCamera();
      onScan(code.data);
    }
  }

  $effect(() => {
    // The video element lives inside the drawer's gated DOM — it only exists
    // while the drawer is open, so track it alongside `open`.
    if (!open || !videoEl) return;
    startCamera();
    return stopCamera;
  });
</script>

<Drawer.Content>
  <Drawer.Header>
    <Drawer.Title>Scan Recipient's QR Code</Drawer.Title>
    <Drawer.Description>Point the camera at the QR code to scan.</Drawer.Description>
  </Drawer.Header>

  <div class="mx-4 overflow-hidden rounded-2xl border bg-muted/40">
    <div class="relative aspect-square max-h-80 w-full">
      <!-- muted + playsinline are required for iOS inline autoplay -->
      <video
        bind:this={videoEl}
        autoplay
        playsinline
        muted
        class="absolute inset-0 h-full w-full object-cover"></video>

      {#if status === 'scanning'}
        <!-- Viewfinder: the drop shadow dims everything outside the square -->
        <div class="pointer-events-none absolute inset-0 grid place-items-center">
          <div
            class="size-48 rounded-2xl border-2 border-primary shadow-[0_0_0_9999px_rgb(0_0_0/0.35)]">
          </div>
        </div>
      {:else if status === 'starting'}
        <div class="absolute inset-0 grid place-items-center">
          <p class="text-sm text-muted-foreground">Starting camera…</p>
        </div>
      {:else}
        <div class="absolute inset-0 grid place-items-center bg-muted/40 p-6 text-center">
          <div class="flex flex-col items-center gap-2">
            <QrCode01Icon class="size-10 text-muted-foreground" />
            <p class="text-sm font-medium">Camera unavailable</p>
            <p class="text-xs text-muted-foreground">{errorMessage}</p>
          </div>
        </div>
      {/if}
    </div>
  </div>

  <Drawer.Footer>
    {#if status === 'error'}
      <Button onclick={startCamera} class="w-full">Try Again</Button>
    {/if}
    <Drawer.Close class={cn(buttonVariants({ variant: 'outline' }), 'w-full')}>
      Cancel
    </Drawer.Close>
  </Drawer.Footer>
</Drawer.Content>
